version: "3.8"

volumes:
  mysql_data:
  redisdata:

services:
  mysqldb:
    build: ./db
    env_file:
      - "./db/db.env"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    command: >
      bash -c "python wait_mysql.py &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  

  redis:
    container_name: redis_contain
    hostname: redis
    image: redis:latest
    # environment:
    #   - REDIS_PASSWORD='root'
    ports:
      - "6379:6379" #이건 맞는거 같아
    volumes:
      - 'redisdata:/data'    
    #   - /usr/local/etc/redis/redis.conf
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest #아마 될거야
    environment:
      - RABBITMQ_USER=guest
      - RABITMQ_PASSWORD=guset #막막하네
    ports:
      - "5672:5672" #rabbitMQ default port
      - "15672:15672" #UI를 위한 port 이건 뭐지?
    expose: #이건 뭐더라?
      - "15672"
    
  celery_worker:
    container_name: celery_worker
    build:
       context: ./backend #수정
       
    ports: [] #이건 왜 비어있지?
    depends_on: 
      - backend 
      - rabbitmq 
    command: sh -c "celery -A backend worker --loglevel=info" #수정




