global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "cadvisor"
    static_configs:
    - targets: ["cadvisor:8080"] # cadvisor 자체가 8080 포트를 사용하므로 8080 포트를 타켓으로 잡는 것이 맞는 것 같음.